apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-k8s
  labels:
    app: node-k8s
spec:
  replicas: 5
  selector:
    matchLabels:
      app: node-k8s
  template:
    metadata:
      labels:
        app: node-k8s
    spec:
      containers:
        - name: node-k8s
          imagePullPolicy: IfNotPresent
          image: node-k8s:1.0.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-k8s-service
spec:
  type: NodePort
  selector:
    app: node-k8s
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
